version: "3.4"
services:
  app:
    container_name: pg
    image: ruby:2.6
    volumes:
      - .:/app
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]

networks:
  default:
    external:
      name: services
